server:
  port: 8080

jwt:
  secret-key: {TU-SECRET-KEY-JWT}
  expiration-ms: 172800000

backend-ecc-public-key: {TU-SECRET-KEY-ECC-PUBLICA}
backend-ecc-private-key: {TU-SECRET-KEY-ECC-PRIVADA}

spring:
  application:
    name: the-workers-gateway

  cloud:
    gateway:
      routes:
        - id: user_verify_credentials
          uri: http://localhost:8081
          predicates:
            - Path=/api/user/verify-credentials

        - id: user_set_ecc_token
          uri: http://localhost:8081
          predicates:
              - Path=/api/user/setEccToken/**
          filters:
              - JWTAuthentication

        - id: auth_public_login
          uri: http://localhost:8083
          predicates:
            - Path=/api/auth/login
        - id: role_user_management
          uri: http://localhost:8082
          predicates:
            - Path=/api/role/**
          filters:
            - JWTAuthentication
            - HybridEccEncryption

        # RUTA DE USUARIOS (REGISTRO DE CLAVE)
        - id: user_management
          uri: http://localhost:8081
          predicates:
            - Path=/api/user/**
          filters:
            - JWTAuthentication
            - HybridEccEncryption

        - id: payment_service
          uri: http://localhost:8081
          predicates:
            - Path=/api/user/payment
          filters:
            - JWTAuthentication
            - HybridEccDecryption
            - HybridEccEncryption