server:
  port: 8080

jwt:
  secret-key: uaobUg2LDENICut8ZxXjVpUL6ob+9+J1oFje1qn6EZi6D+CB2WV6q02AVlCzdxpNNrEKqjDo0nLeVcoaLPu39A==
  expiration-ms: 172800000

backend-ecc-public-key: MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEKvAS0kuUMeVZYJWhgRA8zLYlHe+/8ccp3SJRH5OP0NS4dBAwPIfSMLFai1Cr5u4MHhcu4mm+Yh8XrOQrD+h73A==

spring:
  application:
    name: the-workers-gateway

  cloud:
    gateway:
      routes:
        - id: user_verify_credentials
          uri: http://localhost:8081
          predicates:
            - Path=/api/user/verify-credentials

        - id: auth_public_login
          uri: http://localhost:8083
          predicates:
            - Path=/api/auth/login

        - id: role_user_management
          uri: http://localhost:8082
          predicates:
            - Path=/api/role/**
          filters:
            - JWTAuthentication
            - HybridEccEncryption

        - id: user_management
          uri: http://localhost:8081
          predicates:
            - Path=/api/user/**
          filters:
            - JWTAuthentication
            - HybridEccEncryption